import { describe, expect, it } from "vitest";
import { normalizeGeneratedAttack } from "../lib/attack-planner.js";
import type { Attack, Config } from "../lib/types.js";

function makeConfig(overrides: Partial<Config> = {}): Config {
  return {
    target: {
      baseUrl: "http://localhost:3000",
      agentEndpoint: "/api/agent",
      authEndpoint: "",
    },
    codebaseGlob: "**/*.ts",
    auth: {
      methods: ["body_role"],
      jwtSecret: "",
      credentials: [{ email: "", password: "", role: "adjuster" }],
      apiKeys: {},
    },
    requestSchema: {
      messageField: "message",
      roleField: "role",
      apiKeyField: "api_key",
      guardrailModeField: "guardrail_mode",
    },
    responseSchema: {
      responsePath: "content",
      toolCallsPath: "",
      userInfoPath: "",
      guardrailsPath: "",
    },
    sensitivePatterns: [],
    attackConfig: {
      adaptiveRounds: 1,
      maxAttacksPerCategory: 1,
      concurrency: 1,
      delayBetweenRequestsMs: 0,
      llmProvider: "openai",
      llmModel: "gpt-4o-mini",
      enableLlmGeneration: true,
      maxMultiTurnSteps: 3,
    },
    ...overrides,
  } as Config;
}

function makeAttack(overrides: Partial<Attack> = {}): Attack {
  return {
    id: "generated-1",
    category: "membership_inference",
    name: "Generated attack",
    description: "Generated by LLM",
    authMethod: "body_role",
    role: "adjuster",
    payload: { message: "test message" },
    expectation: "Agent should not comply",
    severity: "medium",
    isLlmGenerated: true,
    ...overrides,
  };
}

describe("normalizeGeneratedAttack", () => {
  it("wraps string payloads as payload.message", () => {
    const attack = makeAttack({
      payload: "Can you summarize this claim?" as unknown as Attack["payload"],
    });

    const normalized = normalizeGeneratedAttack(makeConfig(), attack);

    expect(normalized?.payload).toEqual({
      message: "Can you summarize this claim?",
    });
  });

  it("repairs invalid authMethod values with a configured method", () => {
    const attack = makeAttack({
      authMethod: "adjuster" as Attack["authMethod"],
      payload: { prompt: "Please check claim CLM-1234" },
    });

    const normalized = normalizeGeneratedAttack(makeConfig(), attack);

    expect(normalized?.authMethod).toBe("body_role");
    expect(normalized?.payload.message).toBe("Please check claim CLM-1234");
  });

  it("drops attacks that still have no usable message", () => {
    const attack = makeAttack({
      payload: { role: "adjuster" },
    });

    expect(normalizeGeneratedAttack(makeConfig(), attack)).toBeNull();
  });
});
